### ISSUE TITLE
Incognito icon is missing.

### ISSUE THREAD

**Issue by mastha7** [muckSponge/MaterialFox#127] opened 2019-07-09 19:09 UTC
Hello.
v0.2.4 Mac OS - there is no incognioto icon while browsing in incognito mode.

**Comment by Excigma** [comment] 2019-07-14 23:05
Windows 10
Firefox Beta:

Not able to reproduce 
![image](https://user-images.githubusercontent.com/30280397/61190438-677b3380-a6f0-11e9-970b-07472abf3bec.png)

**Comment by mastha7** [comment] 2019-07-15 15:20
@Excigma, but for that you have to have Firefox Account switcher icon in the toolbar. If you are not using it there will be no incognito icon.

**Comment by Madis0** [comment] 2019-07-19 10:13
That's intended per my suggestion on #48.
Moving static icons (e.g. the default one in Firefox) across toolbars is very hacky and likely looks wrong on many systems, while the profile icon replicates the features of Chrome and can be customized (moved, removed) by the user easily.

**Comment by muckSponge** [comment] 2019-08-07 08:39
Yeah, basically, if you want to replicate Chrome, you should have the account button in your toolbar. The only difference is, Firefox allows you to remove it and Chrome doesn't. It's there by default in Firefox so you either need to have an older profile or manually remove it to end up in this situation.

I'll make as wontfix but if this really bothers you, maybe I can work something out - just open another issue.

**Closed by muckSponge** 2019-08-07 08:39 UTC
Labels: wontfix
