### ISSUE TITLE
Closing tabs

### ISSUE THREAD

**Issue by Schanzation** [muckSponge/MaterialFox#54] opened 2018-11-01 22:31 UTC
Hello!

I am using Windows 10 and with MaterialFox enabled I get this bug when closing tabs. I created a short clip to demonstrate my issue:

https://www.youtube.com/watch?v=PHk0xofoUI4

**Comment by muckSponge** [comment] 2018-12-08 10:41
Please try the latest commit. This is hopefully fixed. Was caused by forcing a specific `max-width` on the tabs. Seems best to just leave anything tab width-related alone or it inevitably causes strange behaviour.

**Comment by Schanzation** [comment] 2019-05-21 21:29
Did you put the code back in? The issue of fast closing tabs with middle click is back.

**Comment by muckSponge** [comment] 2019-05-22 04:46
Oops! I worked it out this time. Firefox applies a `[style]` attribute to tabs if you close a non-end tab when the tabs have filled the tab bar. The style attribute enforces a `max-width` in order to clamp the tab width to the size it was before closing, so that the position of the tab remains the same until the user mouses out of the tab bar. I just choose to enforce a `max-width` except in this situation and it seems to be working fine now, so we can have our cake and eat it too!

**Comment by Schanzation** [comment] 2019-05-22 17:30
Haha, thank you. It works great now! ツ

**Closed** 2019-05-22 23:16 UTC
Labels: bug
