### ISSUE TITLE
animated tracking protection icon (shield) positioned incorrectly

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#165] opened 2019-10-28 09:17 UTC
Although the static shield icon is not displayed, the space for it is still reserved and pushes the animated icon down.
![ff-urlbar-shield-glitch](https://user-images.githubusercontent.com/26410884/67666291-cf861a80-f96b-11e9-96ce-b52549779d0b.png)
Reproduction link: https://www.minecraft.net/en-us/
OS: Win10
FF Version: 70

**Comment by muckSponge** [comment] 2019-11-02 20:41
Can't reproduce on my end. Are there specific tracking settings I need to be using?

**Comment by bucklingspring** [comment] 2019-11-03 05:59
@muckSponge I've encountered this too. 
![image](https://user-images.githubusercontent.com/32025806/68081012-13da4600-fdc4-11e9-98d8-e12ef9638ebd.png)

It happens when using a page with content that Firefox blocks based on your tracking protection settings, as indicated by the coloured shield icon in the address bar.

![image](https://user-images.githubusercontent.com/32025806/68081022-471cd500-fdc4-11e9-9b69-40df59ed58c2.png)
![image](https://user-images.githubusercontent.com/32025806/68081024-5ac83b80-fdc4-11e9-9f6e-78386b666bf0.png)

**Comment by 0x3b0c** [comment] 2019-11-05 11:58
the shield icon height has been changed from 20px to 16px, the tracking-protection-icon-animatable-box element is positioning the animated svg using top: calc(50% - 10px), changed to top: calc(50% - 8px) and it solves the issue on my installation, anyone can check this?


Code added to urlbar.css:

```
#tracking-protection-icon-box > #tracking-protection-icon-animatable-box {
    top: calc(50% - 8px) !important; /* half the height of the sprite */
	height: 16px !important;
}
```

**Comment by leogx9r** [comment] 2019-11-05 19:06
@0x3b0c Yes, works fine on my end.

**Comment by fmeyertoens** [comment] 2019-11-05 21:14
It works indeed. Where did you find: `top: calc(50% - 10px)`? I couldn't see that anywhere?
This whole issue doesn't affect FF 71 btw so we should check that any fix we apply now has no negative effects then.

**Comment by 0x3b0c** [comment] 2019-11-06 08:39
@fmeyertoens from here:
https://hg.mozilla.org/mozilla-central/file/540f0f87e031860704af22b22e1aaecac2d27064/browser/themes/shared/identity-block/identity-block.inc.css

**Comment by fmeyertoens** [comment] 2019-11-06 11:18
Ok I see, but the idea is right. They recently changed it.
https://hg.mozilla.org/mozilla-central/file/tip/browser/themes/shared/identity-block/identity-block.inc.css#l260
```css
#tracking-protection-icon-box:not([hasException])[active] #tracking-protection-icon-animatable-image {
  /* Overrides the default 'display: -moz-box' to prevent icon shifting issue
     with scaled text, see Bug 1591049 */
  display: block;
  background-image: url(chrome://browser/skin/tracking-protection-animation.svg);
...
  height: 16px;
...
}
```

**Comment by BlackTurtle69** [comment] 2019-11-07 15:45
This is still an issue. @muckSponge can you implemented into official release? Im tired of having to manualy fix this after each update.

**Comment by muckSponge** [comment] 2019-11-07 19:43
That animated icon code uses layout tricks to animate the icon, but there are far better techniques using `background-position` or even `-moz-image-rect` instead of all this `position: absolute` and `overflow: hidden` nonsense. Anyway, problem should be fixed now. I took the simplest option on my end and made `#tracking-protection-icon-box` `position: relative` and `display: block`. Tested on 70 and 72. Please confirm it works for you and I'll close.

**Comment by BlackTurtle69** [comment] 2019-11-07 20:44
@muckSponge confirming it works on my end after latest update! Thank you on such quick fix!

**Comment by muckSponge** [comment] 2019-11-07 20:57
No worries. I'm about to implement #147 so hopefully this won't break it again...

**Closed by muckSponge** 2019-11-07 20:57 UTC
Labels: bug
