### ISSUE TITLE
Weird Circles in all the Icons

### ISSUE THREAD

**Issue by ykisana** [muckSponge/MaterialFox#254] opened 2020-08-24 07:53 UTC
These circles are in all my icons, and the bookmark star is always filled in. On Windows.

![image](https://user-images.githubusercontent.com/39938170/91018223-8c590000-e5ac-11ea-8efb-8312df57b401.png)

**Comment by KhushrajRathod** [comment] 2020-08-24 07:56
Duplicate of: https://github.com/muckSponge/MaterialFox/issues/251

**Comment by muckSponge** [comment] 2020-08-25 14:03
If the suggestions in #251 don't resolve the issue, leave a comment in that issue and we can work out a solution.

**Closed by muckSponge** 2020-08-25 14:03 UTC
