### ISSUE TITLE
Show all Bookmarks text out of alignment (bookmarks button menu)

### ISSUE THREAD

**Issue by Schanzation** [muckSponge/MaterialFox#119] opened 2019-06-08 23:20 UTC
Hello! Using FF 67.0.1 on W10.

When opening my bookmarks the text is out of place still.
https://imgur.com/a/8961ooc

Also if I can make a request to make the bookmarks closer together like in the second picture? Looks far better in my opinion.

**Comment by Excigma** [comment] 2019-07-14 23:08
Can reproduce in Windows 10 Firefox Beta:
![image](https://user-images.githubusercontent.com/30280397/61190478-d35d9c00-a6f0-11e9-8120-e66e6f9eadab.png)

Weirdly this is fine:
![C2bB1Kv7W8](https://user-images.githubusercontent.com/30280397/61190482-e2444e80-a6f0-11e9-8757-d0d285bdcb71.gif)

**Comment by muckSponge** [comment] 2019-08-07 11:55
Finally got around to testing on Windows and have fixed the issue. It was due to a forced negative margin, intended to work around a seemingly forced padding of 1.25em on all menu text (Windows-only). Some text didn't have this padding, causing this issue. Turns out I just needed to set `-moz-appearance: none` on `.menu-text` (and set padding to 0) and this removed the magic padding, thus allowing me to remove the negative margin hack.

All is well now so I'll go ahead and close this. The commit touched a few things so if you notice something amiss, create a new issue.

**Closed by muckSponge** 2019-08-07 11:55 UTC
Labels: bug

**Comment by navdeepio** [comment] 2019-08-28 10:45
@muckSponge Hi! get this on macos x too 
<img width="600" alt="Screenshot 2019-08-28 at 4 11 55 PM" src="https://user-images.githubusercontent.com/9297865/63849146-090fc900-c9af-11e9-8324-5abc9761ef1b.png">

Great work with the theme btw, hats off :)

**Comment by muckSponge** [comment] 2019-08-28 10:54
> @muckSponge Hi! get this on macos x too
> <img alt="Screenshot 2019-08-28 at 4 11 55 PM" width="600" src="https://user-images.githubusercontent.com/9297865/63849146-090fc900-c9af-11e9-8324-5abc9761ef1b.png">
> 
> Great work with the theme btw, hats off :)

Glad you like it! Just to clarify, are you pointing out a related issue in your screenshot? It all looks fine to me.

**Comment by navdeepio** [comment] 2019-08-28 10:58
shouldn't the top border of the bookmark menu align with the bottom border of the address menu?

**Comment by muckSponge** [comment] 2019-08-28 11:04
If you mean the address bar, yes it technically should if we compare with how Chrome does it. Feel free to create another issue specifically for that alignment. This particular issue (#119) is actually for the alignment of text in one of the bookmark menu popups, which is a mostly unrelated issue. The issue you're describing relates to almost all popups in general (they're all a few px higher up than Chrome).

**Comment by navdeepio** [comment] 2019-08-28 11:11
done! #149
