### ISSUE TITLE
Send to Device "sent" Dialog broken when sending tab to device

### ISSUE THREAD

**Issue by Excigma** [muckSponge/MaterialFox#183] opened 2019-11-09 07:36 UTC
**Sanity checks (must complete)**
- [X] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release or commit on master

**Describe the bug**
After sending a Tab to a device, the sent dialog flies right and left, then disappears as shown below in Screenshots

**To Reproduce**
1. Hover URL bar
2. Send Tab to device
3. See the sent icon fly around

**Screenshots**

Without Materialfox:
![68prDDW8yA](https://user-images.githubusercontent.com/30280397/68524831-3aeac780-0330-11ea-966a-733003455398.gif)
With Materialfox:
![Y9Z53NIZXS](https://user-images.githubusercontent.com/30280397/68524834-3cb48b00-0330-11ea-829a-f65987c54837.gif)

**System info**
 - OS: Windows 10
 - Firefox version: 70.0.1 (Stable)

**Edit: Additional context**
As shown in the gif above, I did modify my userChrome.css to change the OneTab icon, however, I removed the modifications and the problem still persists

Bug still occurs when the icon is not added to the URL bar

**Comment by Excigma** [comment] 2019-11-09 07:49
~~On a completely unrelated sidenote:
![image](https://user-images.githubusercontent.com/30280397/68525022-44752f00-0332-11ea-9fa7-0c66105cd3cd.png)
Chrome itself's URL Suggestion dropdown is a bit broken lol~~

**Comment by muckSponge** [comment] 2020-04-04 11:45
This should be fixed now. I had to workaround the issue, which is caused by the urlbar buttons automatically hiding after 0.2 seconds when the urlbar is not hovered over. I've now increased the hiding delay to 4 seconds, which gives the confirmation panel enough time to stay visible.

It's a bit of a nasty workaround but should have no ill-effects. It's the opacity transition people actually see, I just set `visibility: hidden` after the opacity transition to improve performance (less rendering to do). The whole reason this was necessary is because the confirmation panel is somehow linked to the button it spawned from, even though there's nothing in the DOM linking them.

I also added some padding so it looks nicer (previously had 0 padding).

Will close the issue because it's been many months since it was opened and you might not respond. If it's still not resolved, let me know and I'll reopen.

**Closed by muckSponge** 2020-04-04 11:45 UTC
Labels: bug
