### ISSUE TITLE
URL Bar dropdown completely glitched in 70.0

### ISSUE THREAD

**Issue by locness3** [muckSponge/MaterialFox#150] opened 2019-08-31 07:13 UTC
Firefox Dev Edition 70.0b2, URL bar's dropdown looks like this :

![Screen Shot 2019-08-31 at 09 11 42](https://user-images.githubusercontent.com/37651007/64060616-8580f280-cbcf-11e9-94a5-00e3510927cc.png)

**Comment by TowelBin** [comment] 2019-09-04 16:58
see #138

**Comment by locness3** [comment] 2019-09-05 16:32
> see #138

Hmmm

**Comment by Excigma** [comment] 2019-09-07 21:32
Able to reproduce on Firefox Beta 70.0b4 on Windows 10

![image](https://user-images.githubusercontent.com/30280397/64480418-70cddb80-d21b-11e9-913f-dfaace8227e1.png)

**Comment by muckSponge** [comment] 2019-09-09 00:30
They've rearranged the search autocomplete dropdown DOM again. I've been experimenting with some code to resolve the issue in 70+ but it's still a work in progress.

The good news is the new code will probably make the layout more stable. The bad news (for me) is the code is completely different to the pre-70 code, making it difficult to have both exist in the theme at the same time. Might need to create a branch for it and switch once 70 is stable.

**Comment by muckSponge** [comment] 2019-09-09 00:31
Oh, that new tab button issue is one I haven't seen before. I am yet to test 70 on Windows though. That might need to be a separate issue, as I'm sure it's unrelated to the search autocomplete.

**Comment by Madis0** [comment] 2019-09-10 14:15
@muckSponge Make sure to also try the "megabar" in about:config, that might be released to stable at some point.

**Comment by locness3** [comment] 2019-09-11 15:59
> @muckSponge Make sure to also try the "megabar" in about:config

What are you talking about ?

**Comment by Madis0** [comment] 2019-09-11 16:06
`browser.urlbar.megabar`. I heard [it is going to be enabled by default](https://bugzilla.mozilla.org/show_bug.cgi?id=1577541) in v71.

**Comment by willone2** [comment] 2019-10-22 19:49
Still having this problem after updating from 69.0.3 to 70.0.

**Comment by Excigma** [comment] 2019-10-23 20:22
> Having this issue after updating from 69.0.3 to 70.0.

https://www.mozilla.org/en-US/firefox/70.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=whatsnew
Firefox has upgraded me to 70.0 Stable

![image](https://user-images.githubusercontent.com/30280397/67430916-b74a8e80-f63f-11e9-91c7-e52c2369b56d.png)

Can anyone else reproduce this weird "New tab" button?
(https://github.com/muckSponge/MaterialFox/issues/150#issuecomment-529148502)

**Comment by fmeyertoens** [comment] 2019-10-24 10:17
This new tab button bug appears only when `Density `is set to `Touch`

**Comment by locness3** [comment] 2019-10-25 10:58
70.0 is now stable @muckSponge

**Comment by willone2** [comment] 2019-10-25 13:27
> 
> 
> > Having this issue after updating from 69.0.3 to 70.0.
> 
> https://www.mozilla.org/en-US/firefox/70.0/releasenotes/?utm_source=firefox-browser&utm_medium=firefox-browser&utm_campaign=whatsnew
> 
> Firefox has upgraded me to 70.0 on Stable
> 
> ![image](https://user-images.githubusercontent.com/30280397/67430916-b74a8e80-f63f-11e9-91c7-e52c2369b56d.png)
> 
> Can anyone else reproduce this weird "New tab" button?
> ([#150 (comment)](https://github.com/muckSponge/MaterialFox/issues/150#issuecomment-529148502))

![bug](https://user-images.githubusercontent.com/11077351/67574974-6e740200-f733-11e9-930e-f49fa871be9a.png)

Yes, this issue is present in 70.0

**Comment by arshwaraich12** [comment] 2019-10-26 04:36
Hi, @muckSponge is it okay if i look into this for Hacktoberfest?

**Comment by muckSponge** [comment] 2019-10-26 05:29
Go for it! Id look into it but unfortunately life has gotten in the way over the past few months.
________________________________

**Comment by arshwaraich12** [comment] 2019-10-26 19:50
Hi, @muckSponge  so i spent quite a lot of time on it and i couldn't fix the URL Bar issue but i was able to fix the shield and new tab icons `[Density: Touch]`. 
I managed to remove the background in `.urlbarView` and also positioned it to not be full-width. (By using padding variables to position it).
However matching the `urlbarView` with urlbar's width is difficult without removing `position: fixed` on `.urlbarView`.
This is how it looks like right now:
![image](https://user-images.githubusercontent.com/29330144/67625154-2246c180-f808-11e9-88c3-6325de471d4d.png)
I don't want to include the changes i made on the urlbar but i will include the changes for fixing the shield icon and the new tab icon. Is it okay if i make a pr for them?

**Comment by muckSponge** [comment] 2019-10-27 20:17
Should be muuuuch less glitched now. Apologies for the delay on this one, life got in the way. I haven't even tried the megabar yet or 71+ so I'm sure that will require a lot more work.

Also, dropped < 70 compatibility. Just can't afford to support old browser DOM - adds way too much bloat.

**Comment by muckSponge** [comment] 2019-11-07 19:54
I'm going to close this. Please open a new issue if you want the megabar to be tracked. I still haven't tested it (got quite a backlog of issues).

Note that the searchbar dropdown is completely messed up. There are some blocking bugs relating to Mozilla's userChrome.css support and use of shadow DOM in 71 or 72 so I've been reluctant to fix it just for 70. It actually impacts a lot of things like tab behaviour but that's a topic for another issue.

**Closed by muckSponge** 2019-11-07 19:54 UTC
Labels: bug
