### ISSUE TITLE
Line behind search bar

### ISSUE THREAD

**Issue by headcomic** [muckSponge/MaterialFox#135] opened 2019-08-07 03:21 UTC
I'm getting a line underneath my tabs that is annoyingly overlapping under my search bar:

<img width="902" alt="image" src="https://user-images.githubusercontent.com/6733647/62592336-b77c8e80-b887-11e9-8cac-f59492089131.png">

Any Ideas how to fix?

**Comment by muckSponge** [comment] 2019-08-07 08:10
Does this occur if you use one of the built-in themes? I'm wondering if maybe you've got a (lightweight) theme installed which has a transparent colour for the toolbars, or perhaps it is absent altogether. What theme are you using? That way I can test this.

**Comment by headcomic** [comment] 2019-08-07 16:05
I figured it out - it was because I was using a chrome theme from firefox.
When I used an alternative "Chrome Dark" theme it corrected. Thanks!

-P

Patrick.Yurick <http://www.patrickyurick.com/>

Design Consultation

619.727.8396

**Comment by muckSponge** [comment] 2019-08-08 08:29
Great! The built-in dark theme (and light theme) has been overridden in MaterialFox to match Chrome's default theme so no need to use a third party one if that's what you're after. Of course, if you prefer the look of a custom theme, go for it.

I'm trying to build MaterialFox to support themes so all themes should be compatible and look more or less like they would in Chrome. That said, if the theme uses some tricks to try to look more like Chrome (for example), and relies on things like carefully aligned background images, it's going to look a bit funky with MaterialFox because it changes the size and alignment of the UI elements and toolbars compared to vanilla Firefox.

I'm marking this as invalid because it's not a bug per se, more like an unsolvable incompatibility (assuming the above is true). Happy to re-open if it turns out MaterialFox is the problem here.

**Closed by muckSponge** 2019-08-08 08:29 UTC
Labels: invalid
