### ISSUE TITLE
Mouse clicks don't work in address bar, tab close etc

### ISSUE THREAD

**Issue by IceMan81** [muckSponge/MaterialFox#94] opened 2019-05-17 18:43 UTC
On Win 7, I find that after I have a number of tabs open (~25 or so), mouse clicks dont work in a number of areas:

1. Address bar
2. Close button
3. Tool bar. 

This only affects the windows with the large number of tabs, any other window with fewer tabs works fine. Keyboard controls are not affected. 

Everything works again if I exit and restart.

**Comment by NICHOLAS85** [comment] 2019-05-17 19:30
With the latest changes to the tabbar I've been experiencing problems as well. Visual glitches when closing tabs and moving tabs as well as the inability to type in the address bar after moving tabs. For me, it didn't seem to matter if I had a large number of tabs open or not. I had to download the latest commit on May 7 to restore proper tab functionality.

Currently running Firefox 67.0 on Linux

**Comment by IceMan81** [comment] 2019-05-17 23:12
I should have stated that I'm using the latest version of the chrome folder, and stilll experiencing these issues.

**Comment by 0076** [comment] 2019-05-18 03:16
Hi, 

I had the same issue with 66.0.5 (64-Bit) on Windows 10. 
Previous commit 1a6061b1017f04678aa988d446ca48c5a8029b1d seems to work correctly as stated by @NICHOLAS85

**Comment by muckSponge** [comment] 2019-05-18 03:25
I only tested it on macOS (68) and a quick test on 67. Changes were mostly to resolve issues on 68. I'll do some more thorough testing later today and see if I can fix this...

**Comment by muckSponge** [comment] 2019-05-18 06:14
Firefox is very finicky about its tab transitions. I pushed it too far in an attempt to implement smoother transitions. These changes have been reverted. I think the regression came from 920837888ff33a179ee7f70f78cd845ce39071d8. Please give the latest commit a go and let me know if you still have the problem.

Only way I could reproduce the problem was to drag a tab so I might be able to re-implement my smoother tab transitions if I use a more specific selector. Will do some experimentation and see how it goes.

**Comment by NICHOLAS85** [comment] 2019-05-18 06:38
Latest commit seems to fix all the previously mentioned issues for me. I'll update if anything begins to act strange.

**Comment by muckSponge** [comment] 2019-05-20 08:08
Thanks for testing. I'll close but feel free to comment if you notice any issues and I'll re-open.

**Closed by muckSponge** 2019-05-20 08:08 UTC
Labels: bug
