### ISSUE TITLE
Chrome-like search results

### ISSUE THREAD

**Issue by RisingFireStar** [muckSponge/MaterialFox#50] opened 2018-10-06 17:56 UTC
Any plans for trying to make chrome-like search results?
![search results](https://user-images.githubusercontent.com/23248936/46574329-278d6000-c9aa-11e8-9057-33e4c58f67b2.png)

**Comment by Madis0** [comment] 2018-10-06 18:15
You should clarify that you mean the _autocomplete_ search results.

**Comment by muckSponge** [comment] 2018-10-07 11:44
Unfortunately the autocomplete search results are not nested in the urlbar so they can't inherit its width but we should be able to do something about the overall style.

**Comment by sagudev** [comment] 2018-10-07 11:57
What about if we made Firefox based browser that act like Chrome (UI and autocomplete for now)

**Comment by muckSponge** [comment] 2018-10-10 02:33
> What about if we made Firefox based browser that act like Chrome (UI and autocomplete for now)

I think that's a bit outside of the scope of this project. You have to consider whether something that involved is actually worth the outcome. I think it's a better idea to style it in a similar fashion to Chrome where possible, but where it can't be helped with a userChrome theme, do it the Firefox way.

A specific fork of Firefox for this theme would further restrict the target audience.

**Comment by Eddi2015** [comment] 2018-11-22 17:47
Yeah IMO keeping up with the latest firefox builds and patches would be too much work, so better we keep it like that. My idea would be to make some sort of platform independet (maybe written in Java?) installer with gui for the 'noobs'. In this installer you can also decide whter to include the different about:config tweaks or not. Maybe I'm going to try to write such an installer. We'll see.

**Comment by Madis0** [comment] 2018-11-22 17:51
@Eddi2015 You may be interested in this: https://github.com/NiklasGollenstede/re-style/issues/21.

For context: [reStyle](https://addons.mozilla.org/en-US/firefox/addon/re-style/) is a Firefox extension for installing and managing userStyles, even the GUI ones on Firefox 57+. You may think of it as a feature Stylish used to have.

Though, the problem with this style specifically would be its scope (a big theme consisting of many files) so while possible, would probably prove to be quite difficult to make auto-updatable.

**Comment by sagudev** [comment] 2018-11-22 17:54
I think we should easily change Firefox installer to install Material-Fox and all configs.

**Comment by Eddi2015** [comment] 2018-11-24 19:46
@Madis0 I thought about some sort of external installer, not as an extension.
@sagudev This also raises the problem about staying up-to-date with the official Firefox installer. I'd rather keep such an installer seperate.

**Comment by sagudev** [comment] 2018-11-25 07:43
@Eddi2015 With Firefox installer I mean [Firefox **stub** installer](https://firefox-source-docs.mozilla.org/browser/installer/windows/installer/StubInstaller.html), which downloads latest Firefox version. In stub installer we just need to add script to download latest Material-Fox and then extract it to Firefox profile folder and change configs that we need.

**Comment by GenkunAbe** [comment] 2019-01-20 00:59
I have made some preliminary modifications, and the current implementation is as follows:
![my implementation](https://user-images.githubusercontent.com/11963004/51433891-62cd4980-1c90-11e9-8fdb-5934232bc18b.gif)

The biggest problem now is that urlbar changes its style before keystrokes, rather than that in chrome:
![chrome](https://user-images.githubusercontent.com/11963004/51433917-e129eb80-1c90-11e9-9d1a-aacdf8cf618a.gif)

My CSS code of urlbar is as follows:
```CSS
#urlbar[focused="true"],
#searchbar[focused="true"]
{
    height: 36px !important;
    background-color: var(--toolbar-field-focus-background-color) !important;
    border: 0px !important;
    border-radius: 10px 10px 0 0 !important;
    box-shadow: rgba(0, 0, 0, 0.16) 2px 4px 6px 0px, rgba(0, 0, 0, 0.16) -2px 4px 6px 0px !important;
}
```

Obviously `[focused="true"]` shouldn't be used here, but I don't know what element selector to use.

**Comment by muckSponge** [comment] 2019-01-20 02:34
@GenkunAbe, how are you setting the urlbar results width? Mine always occupies the full width of the window.

**Comment by GenkunAbe** [comment] 2019-01-20 02:43
I noticed that although the resulting list is full width, the texts and urls inside are always aligned with the urlbar. 

After inspecting the text elements, two variables were found to control the left and right padding: `--item-padding-end` and `--item-padding-start`, so my CSS code is:

```CSS
#PopupAutoCompleteRichResult .autocomplete-richlistbox {
    margin: 0px var(--item-padding-end) 16px calc(var(--item-padding-start) + 22px) !important;
}
```

**Comment by muckSponge** [comment] 2019-01-20 02:46
Just came to the same realisation myself! That's some mighty fine spelunking. I'll take a look at this and see what I can come up with.

Also, you're probably looking for [open] instead of focused.

**Comment by GenkunAbe** [comment] 2019-01-20 03:00
@muckSponge `[open]` is exactly what I'm looking for!

**Comment by muckSponge** [comment] 2019-01-20 04:19
@GenkunAbe, does yours break when you add the searchbar to the nav bar? If I place it before the urlbar, `--item-padding-start` and `--item-padding-end` become unset and if I place it after the urlbar they have incorrect values.

**Comment by GenkunAbe** [comment] 2019-01-20 04:37
@muckSponge Yes, mine is almost the same as yours, but when searchbar before urlbar and the width of browser window is wide enough, everything is normal again.
wide enough:
![3](https://user-images.githubusercontent.com/11963004/51435328-0548f500-1cb0-11e9-8612-7c43107d45d8.png)
too narrow:
![4](https://user-images.githubusercontent.com/11963004/51435334-0f6af380-1cb0-11e9-8eef-ab52480d5088.png)
after urlbar:
![5](https://user-images.githubusercontent.com/11963004/51435337-16920180-1cb0-11e9-9d89-481544ef7626.png)

**Comment by muckSponge** [comment] 2019-01-20 13:03
Tried this kind of tweak on macOS but it doesn't work because there's some kind of OS-styled shadow I can't get rid of:
<img width="218" alt="image" src="https://user-images.githubusercontent.com/5405629/51439508-a1561900-1d0f-11e9-924d-a484cfb1054e.png">
Funnily enough, the screenshot doesn't actually look like it does on my screen. It's not capturing the rounded borders with weird dark artefacts.

**Comment by scorthyn** [comment] 2019-01-20 13:35
how can i add that to my theme? It looks great

> 
> 
> I have made some preliminary modifications, and the current implementation is as follows:
> ![my implementation](https://user-images.githubusercontent.com/11963004/51433891-62cd4980-1c90-11e9-8fdb-5934232bc18b.gif)
> 
> The biggest problem now is that urlbar changes its style before keystrokes, rather than that in chrome:
> ![chrome](https://user-images.githubusercontent.com/11963004/51433917-e129eb80-1c90-11e9-9d1a-aacdf8cf618a.gif)
> 
> My CSS code of urlbar is as follows:
> 
> ```css
> #urlbar[focused="true"],
> #searchbar[focused="true"]
> {
>     height: 36px !important;
>     background-color: var(--toolbar-field-focus-background-color) !important;
>     border: 0px !important;
>     border-radius: 10px 10px 0 0 !important;
>     box-shadow: rgba(0, 0, 0, 0.16) 2px 4px 6px 0px, rgba(0, 0, 0, 0.16) -2px 4px 6px 0px !important;
> }
> ```
> 
> Obviously `[focused="true"]` shouldn't be used here, but I don't know what element selector to use.

where do I insert this code to apply the chrome like search ? :) thanks in advance

**Comment by GenkunAbe** [comment] 2019-01-20 13:48
> 
> 
> Tried this kind of tweak on macOS but it doesn't work because there's some kind of OS-styled shadow I can't get rid of:
> <img alt="image"width="218"src="https://user-images.githubusercontent.com/5405629/51439508-a1561900-1d0f-11e9-924d-a484cfb1054e.png">
> Funnily enough, the screenshot doesn't actually look like it does on my screen. It's not capturing the rounded borders with weird dark artefacts.

@muckSponge I guess my implementation should avoid this problem. Would you mind me to open a pull request? but I am not a designer or programmer, so the style will be a little ugly.

**Comment by GenkunAbe** [comment] 2019-01-20 13:52
@scorthyn It takes a lot more code to achieve the above style, and it's not good enough yet, so you might want to wait for the project to update.

**Comment by muckSponge** [comment] 2019-01-20 13:59
Go for it. Curious to see what your code looks like :) I've worked out a way to get the OS drop shadow to at least follow the border-radius contours but it's a bit of a hack job and doesn't allow you to adjust the drop shadow but it won't work like that on Windows because Windows doesn't enforce a drop shadow.

**Comment by muckSponge** [comment] 2019-01-21 08:22
Made some progress on this in a2cab3c30df06591e02a5aa9df61ee7e2da3fbb2 ([search-results](https://github.com/muckSponge/MaterialFox/tree/search-results) branch). Only tested on macOS thus far and I know Windows won't have a drop shadow. Wanted to get it working on macOS first because it has some nasty limitations regarding the drop shadow (it is enforced by the OS with no way to modify or remove it). This means there has to be a 1-2px visible grey line separating the urlbar from the results, because nothing can be drawn in front of the results and the results have a shadow border forced on them.

<img width="714" alt="image" src="https://user-images.githubusercontent.com/5405629/51461065-4a088500-1db1-11e9-9fb7-6326c84bc796.png">

I might add a smaller, darker 1px `box-shadow` around the urlbar just so it better matches the rather intense shadow cast by the OS. Won't be a perfect match because the OS shadow has some noise applied which is near-impossible to replicate and the`box-shadow` fades out at the bottom.

**Comment by GenkunAbe** [comment] 2019-01-21 09:45
@muckSponge I tested the code in search-results branch on Windows:
![20190121174320](https://user-images.githubusercontent.com/11963004/51466051-46223600-1da4-11e9-8793-22dce0a9d293.png)

**Comment by muckSponge** [comment] 2019-01-21 09:54
Try the latest commit. Added a few Windows-specific tweaks. I think we just need to test Linux now to make sure it behaves like it does on macOS, otherwise I'll need to change some media queries.

**Comment by GenkunAbe** [comment] 2019-01-21 10:00
@muckSponge It's perfect now!

![image](https://user-images.githubusercontent.com/11963004/51466924-41f71800-1da6-11e9-8920-f19c173d1c20.png)

**Comment by muckSponge** [comment] 2019-01-22 05:52
Still quite a few tasks to complete to be able to close this issue. I'll list them below and tick them off once complete:

- [ ] Hide identity box text and urlbar icons, and show favicon when `#urlbar[open]`.
- [ ] Disable `pointer-events` on identity box when `#urlbar[open]`.
- [ ] Replace search icon with Chrome search icon (it's a bit smaller).
- [ ] Highlighted/focused search result behaves differently to Chrome (investigate changing colour or removing behaviour).
- [ ] Search go icon might need to be removed or restyled.
- [ ] Update searchbar styling (this is a rather big one).

**Comment by TowelBin** [comment] 2019-01-26 04:00
> 
> 
> @muckSponge I tested the code in search-results branch on Windows:
> ![20190121174320](https://user-images.githubusercontent.com/11963004/51466051-46223600-1da4-11e9-8793-22dce0a9d293.png)
Can you share the code for that? right now I'm using the muckSponge version at [a2cab3c](https://github.com/muckSponge/MaterialFox/commit/a2cab3c30df06591e02a5aa9df61ee7e2da3fbb2) on windows and the suggestions still overflow past the end of the URL bar. 

Add this to the task list:

- [ ] Show favicon of the #1 URL suggestion when typing  to the left urlbar, or favicon of the search engine if the #1 suggestion is a search suggestion. 
- [ ] Replace the default favicon and globe icon with chrome's. Use this icon in the URL bar when a suggested website doesn't have a favicon
- [ ] fine tune shadow and border radius

**Comment by GenkunAbe** [comment] 2019-01-26 04:15
@TowelBin The figure above is using the code at commit [7a23bea](https://github.com/muckSponge/MaterialFox/commit/7a23bea47ecd002ccac23268a8e871582329c094). However, you can also try the latest commit.

**Comment by muckSponge** [comment] 2019-01-26 04:19
> Can you share the code for that? right now I'm using the muckSponge version at [a2cab3c](https://github.com/muckSponge/MaterialFox/commit/a2cab3c30df06591e02a5aa9df61ee7e2da3fbb2) on windows and the suggestions still overflow past the end of the URL bar.

Should be able to just grab the latest commit on master.

> Show favicon of the first URL suggestion when typing  to the left urlbar, or favicon of the search engine if the first suggestion is a search suggestion.

I'll have a look but I doubt this is possible because I don't think the urlbar element has access to a) the favicon of the search engine and b) the favicons of any of the suggestions shown in the search results box.

> Replace the default favicon and globe icon with chrome's. Use this icon in the URL bar when a suggested website doesn't have a favicon

Should be doable. From what I understand the globe icon _is_ the default favicon.

> fine tune shadow and border radius

I'd say it's pretty close as it is. Only obvious thing is the shadow fades out between the urlbar and the search results box but without some serious over-engineering I can't do much about that (I tried for a few hours and gave up).

![image](https://user-images.githubusercontent.com/5405629/51782491-5445cd00-217d-11e9-8c9c-be052e84dfb6.png)

**Comment by TowelBin** [comment] 2019-01-26 06:39
> 
> 
> @TowelBin The figure above is using the code at commit [7a23bea](https://github.com/muckSponge/MaterialFox/commit/7a23bea47ecd002ccac23268a8e871582329c094). However, you can also try the latest commit.

![broken](https://user-images.githubusercontent.com/43922012/51783619-50da2380-2134-11e9-9993-fb29f293fa86.png)
It doesn't seem to work on my system. In fact, the font color blends in with the background. It doesn't work like it does on your system. any ideas for why this is?

**Comment by muckSponge** [comment] 2019-01-26 07:51
Not sure. Are you using any lightweight themes or add-ons? What OS? Kinda looks like it thinks a dark lightweight theme is active so it's making the text white.

**Comment by TowelBin** [comment] 2019-01-26 18:48
> 
> 
> Not sure. Are you using any lightweight themes or add-ons? What OS? Kinda looks like it thinks a dark lightweight theme is active so it's making the text white.

The only addon that I use that changes the theme is MaterialFox helper. I'm not using any lightweight themes. I think the problem is that I am using the default material theme. I don't know why it still overflows past the end of the urlbar though.

**Comment by muckSponge** [comment] 2019-01-27 04:19
You should no longer need MaterialFox Helper because of recent changes to the theme which essentially accomplish the same thing (that is, applying Material light or dark colour palette and dark mode when private browsing). I'd disable or uninstall it and see if that helps but to be honest, having it enabled shouldn't really cause issues.

My suggestion is, try in a fresh profile (go to `about:profiles`) and if that doesn't work, try the different built in themes (default, light, dark) and let me know if one or more of them work and we might be able to narrow down the problem. Only other thing I can think of is the Windows theme. I've only tested recently on Windows 10 with a specific theme colour (darkish grey), so perhaps it is breaking if you use a very light or very dark colour.

**Comment by TowelBin** [comment] 2019-01-28 00:46
Dark theme - font color is gray and readable
Light theme - font color is the same as dark theme and is very readable
default theme - font color is very light gray (possibly the same as other themes?) and is not readable
All 3 themes have the search suggestions extend past the end of the url bar, but only when materialfox helper is enabled. changing the profile doesn't do anything.

I think I just need to change the font color manually. Try testing it again with the default theme.

**Comment by apersonnamedmike** [comment] 2019-01-30 16:47
![image](https://user-images.githubusercontent.com/10731372/51997404-e696eb00-2473-11e9-8805-f2329aead73a.png)

My search suggestions recently started looking like what's in the above image (from a previous comment) on a fresh install of firefox and just with MaterialFox (no additional themes installed) and this stuff for scrollbars:
https://github.com/endeavoursc/firefox-overlay-scrollbars-win10

I noticed that it started giving this behavior after updating to firefox 65 on windows 10.
I was using the default theme but have since been using the dark theme for now as that lets me read the search suggestions. It seems to me that the font color is always on light or white no matter which theme I'm using.

**Comment by muckSponge** [comment] 2019-02-02 05:08
Worked out this bug was present in FF64 but masked by the different window colouring behaviour (which usually resulted in dark text on a light background). In FF65 this changed so often you'll get light text on a darker background now, and `#PopupAutoCompleteRichResult` was inheriting its colour from the parent, which is `#main-window`, hence it resulted in light colour text. I've removed the line which forces colour inheritance, tested on macOS and Windows 10 and seems to work fine. Should inherit the colour from the lightweight theme popup text colour variable now.

**Comment by muckSponge** [comment] 2019-05-29 12:54
Ticked enough of the items off the list to call this done IMO. Still some work to do here and there but that's true of almost every part of the theme. Many fixes are currently in the [popup-refresh](https://github.com/muckSponge/MaterialFox/tree/popup-refresh) branch, which I'll be pushing to master after a bit more testing but any further bugs can have their own issue.

**Closed by muckSponge** 2019-05-29 12:54 UTC
Labels: enhancement
