### ISSUE TITLE
Urlbar broken in Fx74 beta

### ISSUE THREAD

**Issue by kulocora** [muckSponge/MaterialFox#207] opened 2020-02-12 04:23 UTC
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release or commit on master

**To Reproduce**
Firefox 74

**Screenshots**
![图片](https://user-images.githubusercontent.com/12947678/74302629-1a4c6680-4d92-11ea-946d-e6494f1dbf8c.png)

**System info**
 - OS: Windows 10
 - Firefox version: 74

**Comment by fmeyertoens** [comment] 2020-02-12 10:54
To clarify, this is the focused state of the URL bar.
Reproducible by cycling through the UI elements with the TAB key.

**Comment by trbn1** [comment] 2020-02-13 04:52
Until this is fixed you can disable the new urlbar by setting `browser.urlbar.update1` to `false` in about:config.

**Comment by muckSponge** [comment] 2020-02-13 12:30
Should be fixed now; you'll need to switch to 74 branch.

**Comment by Write** [comment] 2020-02-13 19:47
> 
> 
> Should be fixed now; you'll need to switch to 74 branch.

Thanks ! 
While the url bar in focused state seems to be fixed, there's an other bug with urlbar results/predictions. While typing if results/predictions are large enough, the width of the bar will change.

**Comment by muckSponge** [comment] 2020-02-14 08:50
I'm unable to reproduce that issue. Could you provide a screenshot?

**Comment by Write** [comment] 2020-02-14 15:19
URLBar without results/predictions : https://prnt.sc/r2d3ch
With prediction : https://prnt.sc/r2d3o0

As you can see the width changed. And it does that while typping

**Comment by Aire-One** [comment] 2020-02-17 18:08
This is the exact urlbar glich I have with firefox nightly and we discussed in #201.

I can confirm the 74 branch fix it.

I also have the urlbar width changes. It seems to be related to the suggestions text length: the bar width is relative to the suggested text width. As shown on @Write screenshots, when I have long url in the suggestions, the urlbar is wider, but when the suggestions become smaller, the urlbar follows and become smaller.

**Comment by muckSponge** [comment] 2020-04-03 13:43
I'm unable to reproduce the width change on macOS. Are you using Windows 10 and do you have any spacers in your nav bar? Looks like there might be spacers from the screenshot but I've tested with spacers and still don't get the problem on my end.

**Comment by Write** [comment] 2020-04-03 13:53
> 
> 
> I'm unable to reproduce the width change on macOS. Are you using Windows 10 and do you have any spacers in your nav bar? Looks like there might be spacers from the screenshot but I've tested with spacers and still don't get the problem on my end.

Yes i'm on W10
Not sure what spacers is, is it the 'flex spaces' you can add to add blank space ? 
Anyway i tried to re-enable browser.urlbar.update1 to test, it again. 
I removed the spacers and it seems working correctly (the width isn't changing). 
It seems to only bug when spacers are added to the left of the search bar.

**Comment by Aire-One** [comment] 2020-04-04 12:21
> I'm unable to reproduce the width change on macOS. Are you using Windows 10 and do you have any spacers in your nav bar? Looks like there might be spacers from the screenshot but I've tested with spacers and still don't get the problem on my end.

Linux on my side. I updated to latest nightly 76.0a1 (2020-04-03) and switched back to master. The problem persists...

Removing "flexible space" from the Customize tab fix the bug tho.

**Comment by muckSponge** [comment] 2020-04-16 02:04
Let's move tracking of this flexible width bug to #223, as the original bug has been resolved.

**Closed by muckSponge** 2020-04-16 02:04 UTC
Labels: bug, fix pending
