### ISSUE TITLE
Popup panels missing background

### ISSUE THREAD

**Issue by Zoahr** [muckSponge/MaterialFox#156] opened 2019-10-18 12:01 UTC
![Firefox Passwort Fenster](https://user-images.githubusercontent.com/44004296/67092542-c3ea6500-f1af-11e9-8c58-2a2e7700db5a.jpg)
![Firefox Versionsfenster](https://user-images.githubusercontent.com/44004296/67092548-c6e55580-f1af-11e9-88a9-a82136da6107.jpg)

**Comment by fmeyertoens** [comment] 2019-10-18 14:35
The problem is afaik that the selector in this rule doesn't apply anymore since the panel arrowcontent was moved into a custom element (shadow DOM) and the selector doesn't cross this boundary.
https://github.com/muckSponge/MaterialFox/blob/9ba6b1b23016eb31f19d2fb68f926f69aeeb2ed0/chrome/popup/popup.css#L211-L221
The rule should be changed to
```css
panel:not(.tooltip-xul-wrapper)::part(arrowcontent)
```
but the `::part()` pseudo-element is not supported in userChrome.css yet as tracked by this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1575507.
A workaround would be to just use the `.panel-arrowcontent` selector but I don't know whether that breaks anything.

**Comment by Zoahr** [comment] 2019-10-18 16:07
Tried as you suggested just with `.panel-arrowcontent` and it worked. So far nothing broken but I have not checked everything. Thanks very much.

**Comment by Zoahr** [comment] 2019-10-18 16:14
I think it breaks the position of the window somehow (though it shouldn't because there is no positioning css in the rule). The window appears slightly left of the button that made it appear.
![Anmerkung 2019-10-18 181006](https://user-images.githubusercontent.com/44004296/67110478-256ffb00-f1d3-11e9-9ad0-eed2dd042ed7.jpg)

**Comment by fmeyertoens** [comment] 2019-10-18 17:36
Are you sure the positioning issue is connected to this change?

**Comment by fmeyertoens** [comment] 2019-10-18 18:46
I experimented a bit and it looks better for me when I change the rule in `popup.css` at `line 193` to

margin: **-10px** **-34px** -18px !important;

**Comment by Zoahr** [comment] 2019-10-18 20:35
> 
> 
> Are you sure the positioning issue is connected to this change?

No, I'm pretty sure it has nothing to do with the change - it's just that previously it wasn't noticable because of the transparent background color (or I just never paid enough attention)

I tried your new margin and now the drop downs look perfect :-) Thanks for the help!

**Comment by muckSponge** [comment] 2019-11-02 16:17
This should be fixed now. Tested a few popups and they seem to be working. Will close but comment if you're still experiencing problems and we can look into this again.

**Comment by redfoxseattle** [comment] 2019-11-05 02:02
This worked for me, thank you!

**Comment by sikaiser** [comment] 2020-01-20 10:38
I'm still having this issue. Any ideas?

- Windows 10
- Firefox 72.0.1
- using the latest commit on the 72 branch (https://github.com/muckSponge/MaterialFox/commit/f3d6ed009ef8e06bc91c799dc69471d0742f17f6)

**Comment by IRlyLikeBac0n** [comment] 2020-03-31 04:02
Windows 10, Nightly 76.0a1 and still have problems. 

I couldn't find the code mentioned by above users because I downloaded the most recent set of files as of the time of this comment.

**Comment by muckSponge** [comment] 2020-03-31 04:09
I haven't been testing nightly for quite some time because it often changes by the time it gets to beta and no point developing for a moving target.

Could you test on 75 and see if the problem persists? Also please provide a screenshot so I know what popup has the problems (in 75 or 76).

**Comment by IRlyLikeBac0n** [comment] 2020-03-31 04:33
![Annotation 2020-03-31 003202](https://user-images.githubusercontent.com/62923135/77987168-1b583980-72e7-11ea-8fb0-50a3e1d6d067.png)
Thanks for the fast response. I just tried on the 75 beta channel, and the issue isn't there. I've attached a screenshot of the issue in my 76 Nightly though.

**Comment by muckSponge** [comment] 2020-03-31 04:38
Alright, so is that a bookmarks folder in the bookmarks toolbar, or a special button? Just trying to work out what element that is so I can work on it. Thanks.

**Comment by IRlyLikeBac0n** [comment] 2020-03-31 04:41
Ah sorry, it's a bookmarks folder. Hope that helps. This must be the result of some new change present in 76, if 75 works perfectly fine.

**Comment by muckSponge** [comment] 2020-03-31 04:43
Looks like it's in the nav bar instead of the bookmarks toolbar, must be a new Firefox thing I haven't familiarised myself with yet. I'll have a look when I have some free time.

**Comment by IRlyLikeBac0n** [comment] 2020-04-09 17:59
Oh I don't think I clarified this earlier, but the issue is not just with the nav/bookmarks toolbar. The same thing happens with the right-click context menu and pop-ups (like on a website's form). However the popup when clicking on the 3 vertical dots (for "Open menu") is still normal.

**Comment by redfoxseattle** [comment] 2020-04-09 22:38
I'm having the same issue in Developer Edition 76.0b1 on Catalina.

**Comment by muckSponge** [comment] 2020-04-10 14:33
This should be fixed in the new 76 branch. Will make its way to master once 76 moves out of beta.

I'm going to close this now because it should be resolved and I think it's a good idea to open a new issue for any other missing popup backgrounds to make it easier to track. This one's piggybacking off an old issue and while very similar, they impact on different elements (originally this issue was for panels – the ones with arrows, but the later issues were for menupopups – no arrows, different DOM).

**Closed by muckSponge** 2020-04-10 14:33 UTC
Labels: bug
