### ISSUE TITLE
Left tab cut off

### ISSUE THREAD

**Issue by Kastilo** [muckSponge/MaterialFox#60] opened 2019-01-27 04:15 UTC
Hello,

It seems like the left most tab isn't displayed correctly, I've reinstalled and such, and it seems to be a persistent issue. Adding a spacer shows that that part of the UI is "loading" but it just is cut off somehow

![image](https://user-images.githubusercontent.com/14260317/51796427-eb2f7b00-21b7-11e9-8042-70158dd121bb.png)

**Comment by Kastilo** [comment] 2019-01-27 04:30
OS: Kubuntu 18.10, GTK3 Theme: Breeze
![image](https://user-images.githubusercontent.com/14260317/51796488-a4428500-21b9-11e9-90ba-51ea3c05dc1a.png)

Browser Customization:
Dark Theme, Normal, Title bar off

**Comment by muckSponge** [comment] 2019-01-27 04:37
Does it occur if you have no pinned tabs or is it only pinned tabs which get cut off?

**Comment by Kastilo** [comment] 2019-01-27 04:39
All tabs get affected, no matter what, 
Also, seems that in fullscreen it's cut off, in minimized/windowed it's not, and normal fully open (I'm guessing that's maximized) is what you see in the screenshot

**Comment by Kastilo** [comment] 2019-01-27 04:40
![image](https://user-images.githubusercontent.com/14260317/51796546-5dee2580-21bb-11e9-9d94-ae21cab019a2.png)
![image](https://user-images.githubusercontent.com/14260317/51796547-60e91600-21bb-11e9-935b-96cfd13d8f3d.png)
(windowed mode)

**Comment by muckSponge** [comment] 2019-01-27 08:50
Still not sure why this is happening. I only have Ubuntu to test and it doesn't have this issue.

**Comment by istir** [comment] 2019-01-27 21:05
I have the same issue on Windows 10, in windowed mode there is a gap between border and the tab and in fullscreen there isn't.

I edited tabbar.css to include 
```
#TabsToolbar{
margin-left:-40px;
}
```

And it fixes the windowed one but now it's cut off in fullscreen. Tried
```
#TabsToolbar:not([inFullscreen]) {
	margin-left: -40px;
}
```
but it didn't work. Any ideas?

**Comment by printer83mph** [comment] 2019-01-28 05:49
Yep having this same issue on Windows 10

**Comment by muckSponge** [comment] 2019-01-28 07:35
This is odd. I've been unable to reproduce this on Windows 10 in any window mode.

**Comment by istir** [comment] 2019-01-28 17:03
It doesn't occur if you have menu bar activated, maybe that's why?

**Comment by muckSponge** [comment] 2019-01-30 04:17
Is everyone using Firefox 64 or 65, or a mix? Is anyone able to use the Browser Toolbox to inspect the tab bar to see what might be causing it? Kinda looks like something has `overflow: hidden` and/or `#tabbrowser-tabs` needs additional (say, 8px) padding on the left and a parent needs some negative margins to offset it.

**Comment by printer83mph** [comment] 2019-01-30 05:02
Thanks for investigating this issue. Will check tomorrow

**Comment by Kastilo** [comment] 2019-01-30 05:15
66 & 65 are affected for me (Nightly and Base), although I am not versed in this so, not sure how to investigate that part. Just thought I'd give that input

**Comment by Kastilo** [comment] 2019-02-03 13:38
Fresh profile in Firefox beta, base, and nightly, still all doing the same thing for some weird reason

**Comment by marcelharinck** [comment] 2019-02-03 13:47
I had this problem aswell. I reinstalled MaterialFox and then the problem
was fixed.

**Comment by MikoMagni** [comment] 2019-02-06 01:42
Same issue on MacOS 10.14.2 with Firefox Developer Edition 66.0b5

<img width="112" alt="screen shot 2019-02-06 at 12 06 44 pm" src="https://user-images.githubusercontent.com/2527231/52315706-0c8a3580-2a08-11e9-94a5-5edbb6fdc57f.png">

Fixed it by changing line 85 on tabbar.css from 

`#tabbrowser-tabs:not([overflow]) .arrowscrollbox-scrollbox
{
	margin: 0 -8px !important;
}`

to 

`#tabbrowser-tabs:not([overflow]) .arrowscrollbox-scrollbox
{
	margin: 0 8px !important;
}`

Result
<img width="105" alt="screen shot 2019-02-06 at 12 06 57 pm" src="https://user-images.githubusercontent.com/2527231/52315798-6f7bcc80-2a08-11e9-97d3-7e50cac69dde.png">

**Comment by muckSponge** [comment] 2019-02-06 13:12
Should hopefully be fixed now. While I was able to reproduce on macOS eventually, I couldn't get it to occur on Win10, so I've been unable to test that.

**Comment by MikoMagni** [comment] 2019-02-07 04:26
> Should hopefully be fixed now. While I was able to reproduce on macOS eventually, I couldn't get it to occur on Win10, so I've been unable to test that.

@[muckSponge](/muckSponge) confirming that is fixed on MacOS. Thank you

**Comment by muckSponge** [comment] 2019-02-16 23:01
Closing this due to inactivity so I assume it is fixed for Windows users too. If not, let me know and I'll reopen.

**Closed by muckSponge** 2019-02-16 23:01 UTC
Labels: bug
