### ISSUE TITLE
Scrollbuttons aren't hidden

### ISSUE THREAD

**Issue by fmeyertoens** [muckSponge/MaterialFox#206] opened 2020-01-23 11:55 UTC
**Sanity checks (must complete)**
- [x] I have read and followed the installation instructions in the README
- [x] I have not modified the userChrome.css file
- [x] I have tested the latest release or commit on master

**Describe the bug**
The scrollbuttons in scrollable menupopups (e.g. in the favorites bar) are visible although they shouldn't be.
https://github.com/muckSponge/MaterialFox/blob/f3d6ed009ef8e06bc91c799dc69471d0742f17f6/chrome/popup/popup.css#L142-L147
These selectors don't seem to apply.

**To Reproduce**
1. Open a folder in the favorites bar with many items.
2. Scrollbuttons are shown at the top and bottom.

**System info**
 - OS: Windows 10
 - Firefox version: 72.0.2

**Comment by iamthekings5** [comment] 2020-01-24 12:37
https://i.imgur.com/RN2down.png

Seems to be related, this occurs on my laptop's monitor but not on the external monitor connected to my laptop. Not sure why.

**Comment by muckSponge** [comment] 2020-02-13 10:34
Should be fixed but there may be regressions. Because of Mozilla's use of shadow dom and refusal to allow userChrome.css to style it properly, I have to use a shotgun approach to the selectors, which means they may affect other parts of the UI.

**Closed** 2020-03-22 14:12 UTC
Labels: bug, fix pending
